### ISSUE TITLE
Add licence

### ISSUE THREAD

**Issue by ingomueller-net** [AEGEE/oms-core#1]
The project could be open-sourced, with the approval of AEGEE-Europe and the ITC board.

Pavel already mentioned that open-sourcing would not be ruled out.

In any case, one licence should be found - MIT?

---
- Bitbucket: https://bitbucket.org/ingomueller-net/oms-core/issue/1
- Originally reported by: [grasshopper](http://bitbucket.org/grasshopper)
- Originally created at: 2015-05-16T14:52:45.082

**Comment by ingomueller-net** [comment]
Apache Licence would be just fine, in this case better than the MIT one IMHO

https://bitbucket.org/bitbeaker-dev-team/bitbeaker/src/6695a3c817d40249613d4a55084950aea7690241/LICENSE.md

---

Original comment by: [grasshopper](http://bitbucket.org/grasshopper)

**Comment by ingomueller-net** [comment]
added licence, closes #1

→ <<cset 5d82fc10e357>>

---

Original comment by: [grasshopper](http://bitbucket.org/grasshopper)

**Comment by linuxbandit** [comment]
5d82fc1 closes this, for some reason it was still open
