### ISSUE TITLE
Set-up test infrastructure and start writing tests

### ISSUE THREAD

**Issue by ingomueller-net** [AEGEE/oms-core#12]
I do not know a lot of test frameworks for web technologies. Probably we need a couple of them for different levels of tests (nodejs unit tests, a test REST client, etc). Also they should be run automatically on every push.

---
- Bitbucket: https://bitbucket.org/ingomueller-net/oms-core/issue/12
- Originally reported by: Ingo Müller
- Originally created at: 2015-10-19T21:43:30.136

**Comment by ingomueller-net** [comment]
Making the unit tests run on travis is not trivial because no LDAP server runs there. [passport-ldapauth](https://github.com/vesse/passport-ldapauth/) starts an [ldapjs server](http://ldapjs.org/server.html) for that purpose. I guess we could do something similar.

**Comment by linuxbandit** [comment]
And FYI, for this purpose I had added [this file](https://github.com/AEGEE/oms-development-vm/blob/0a369a0aa9d64a12a4b8354d00005fd87f25a92e/puppet/modules/aegee_ldap/files/testdata/20-automatedtests.ldif) that contains some easy structure. It just needs to be put under the top level (o=aegee,c=eu)
