### ISSUE TITLE
Design and implement permissions

### ISSUE THREAD

**Issue by ingomueller-net** [AEGEE/oms-core#15]
It is clear that not every user has the right to do everything. Examples:
- Only me, administrators, and maybe the board of my antenna should be able to modify my profile.
- Only admins should be able to create and delete bodies.
- Only boards should be able to modify details of their bodies.
- Only members of a body should see its members.
- Members of some bodies should be seen by everyone (CD, JC, ...).

The actual list is much longer and partially defined by [DPPS](https://www.dropbox.com/s/igm3szna0fimw3n/Data%20Privacy%20Visuals%20v0.25.pdf?dl=0).

However we still have to figure out on which level we want to implement them (in LDAP, in NodeJS, ...?). Since Agora will change the DPPS every 6 months, it should something that is reasonably easy to change. Finally we should implement a first set of permissions to check our design and to show something to users so that they can give feedback...

---
- Bitbucket: https://bitbucket.org/ingomueller-net/oms-core/issue/15
- Originally reported by: Ingo Müller
- Originally created at: 2015-10-19T21:56:16.861

**Comment by ingomueller-net** [comment]
Related to #5.

---

Original comment by: Ingo Müller

**Comment by linuxbandit** [comment]
If it is not automagic already with the authentication, we can push it to a later milestone
