### ISSUE TITLE
Move project to Github

### ISSUE THREAD

**Issue by ingomueller-net** [AEGEE/oms-core#16]
This will
- increase visibility,
- make it easier for users to join who know Github (and there are more of them than those who know bitbucket),
- make it possible to integrate with more tools (such as [travis](https://travis-ci.org/)).

Concretely, we need to create a user (or organization). I'd propose to name the user/organisation at Github just "aegee" (without reference to ITC).

Also we should try to migrate issues etc together with the git code. A first research showed a few scripts. We should try them out on a private repository first before doing it for real.
- http://stackoverflow.com/questions/21844109/move-issues-from-bitbucket-to-github
- https://gist.github.com/nidico/3778347
- http://webapps.stackexchange.com/questions/49729/how-can-i-import-issues-from-bitbucket-to-github

---
- Bitbucket: https://bitbucket.org/ingomueller-net/oms-core/issue/16
- Originally reported by: Ingo Müller
- Originally created at: 2015-10-26T16:13:41.684

**Comment by ingomueller-net** [comment]
(trivial) why no reference to ITC?

---

Original comment by: [grasshopper](http://bitbucket.org/grasshopper)

**Comment by ingomueller-net** [comment]
Can be debated, but In my vision we could have any AEGEE related software hosted there. Then it would be the one and only go-to place for nerds within AEGEE ;)

---

Original comment by: Ingo Müller

**Comment by ingomueller-net** [comment]
but I believe that the few nerds within AEGEE are already in ITC, that's why I asked :D

---

Original comment by: [grasshopper](http://bitbucket.org/grasshopper)

**Comment by ingomueller-net** [comment]
@ingomueller-net, I'd assign you to the task because at https://github.com/organizations/new it asks me for a billing address, and I am not sure what's the procedure that the ITC has in this case (itc-board-l vs some gmail address shared)

for the name thing (still trivial) my point was there, another added value though to your opinion is that we promote AEGEE as whole. I don't mind either way

[This is me on github](https://github.com/serviceman)

---

Original comment by: [grasshopper](http://bitbucket.org/grasshopper)

**Comment by ingomueller-net** [comment]
OK, will do that tomorrow. What should be the name? `aegee`, `aegee-europe`, `aegee-itc`, something else? I favor one of the first two...

---

Original comment by: Ingo Müller

**Comment by ingomueller-net** [comment]
**Very important**: We may need to import our bitbucket projects to a _personal_ account first, and then convert that into an organization because organizations may not import imports (see [this issue](https://github.com/vbabiy/bitbucket_issue_migration/issues/21)).

---

Original comment by: Ingo Müller

**Comment by ingomueller-net** [comment]
alright, I will handle the transition then

the registration, for some reason I prefer just AEGEE over AEGEE-Europe

---

Original comment by: [grasshopper](http://bitbucket.org/grasshopper)

**Comment by ingomueller-net** [comment]
I was playing around the last hour or so with a [playground organization](https://github.com/g9NmIkehCleu) and [this migration script](https://github.com/ingomueller-net/bitbucket_issue_migration). I fixed an issue with UTF-8 encoding, but now I get 403 errors from Github. I have the impression I am now being blocked by Github. Not sure what to do next...

---

Original comment by: Ingo Müller

**Comment by ingomueller-net** [comment]
BTW, if you want to create the organization, just use itc@aegee.org as billing address.

---

Original comment by: Ingo Müller

**Comment by ingomueller-net** [comment]
ah that's perfect, all I needed

(why that weird name for the organisation? :D )

---

Original comment by: [grasshopper](http://bitbucket.org/grasshopper)

**Comment by ingomueller-net** [comment]
Randomly generated :P

---

Original comment by: Ingo Müller

**Comment by ingomueller-net** [comment]
Live at https://github.com/AEGEE (I invited you), now onto the import 

---

Original comment by: [grasshopper](http://bitbucket.org/grasshopper)

**Comment by ingomueller-net** [comment]
Import gives me errors: after the 5th issue I get this. Also, the flag -f doesn't work...

 File "migrate.py", line 122, in format_comment
    comment['user'].encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6: ordinal not in range(128)

I am using the repo you forked

---

Original comment by: [grasshopper](http://bitbucket.org/grasshopper)

**Comment by ingomueller-net** [comment]
I was able to fix this by changing line 122 to comment['user'].encode('utf-8').decode('utf-8'). Then later I got a 403 error and couldn't continue testing...

---

Original comment by: Ingo Müller

**Comment by ingomueller-net** [comment]
alright, this is better but still error (a different one though)

Traceback (most recent call last):
  File "migrate.py", line 304, in <module>
    push_issue(gh_username, gh_repository, issue, body, comments)
  File "migrate.py", line 268, in push_issue
    gh_repository
  File "/usr/local/lib/python2.7/dist-packages/pygithub3/services/issues/comments.py", line 55, in create
    return self._post(request)
  File "/usr/local/lib/python2.7/dist-packages/pygithub3/services/base.py", line 139, in _post
    response = self._client.post(request, data=input_data, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pygithub3/core/client.py", line 89, in post
    response = self.request('post', request, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pygithub3/core/client.py", line 71, in wrapper
    return func(self, verb, request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pygithub3/core/client.py", line 80, in request
    GithubError(response).process()
  File "/usr/local/lib/python2.7/dist-packages/pygithub3/core/errors.py", line 36, in process
    self.response.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 837, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.github.com/repos/serviceman/oms-core-testimport/issues/36/comments?per_page=100

any idea why this is now forbidden? it looks like the same message you have..

maybe i'll try tomorrow

---

Original comment by: [grasshopper](http://bitbucket.org/grasshopper)

**Comment by ingomueller-net** [comment]
btw, it stops at 10

---

Original comment by: [grasshopper](http://bitbucket.org/grasshopper)
EDIT serviceman to avoid cross-ref of issues

**Comment by ingomueller-net** [comment]
also the -f flag doesn't work because bitbucket api are broken: [this page](https://api.bitbucket.org/1.0/repositories/aegeeitc/oms-core/issues/?start=16) should give only the 17th issue, but it gives only the first (similarly, start=15 doesn't give the last 2 but the first 2)

---

Original comment by: [grasshopper](http://bitbucket.org/grasshopper)

**Comment by ingomueller-net** [comment]
their API are so broken that "limit" doesn't perform according to [the docs](https://confluence.atlassian.com/bitbucket/issues-resource-296095191.html#issuesResource-GETalistofissuesinarepository'stracker). but it performs the dual of start... (i.e. ALMOST what start should do)

---

Original comment by: [grasshopper](http://bitbucket.org/grasshopper)

**Comment by ingomueller-net** [comment]
when does it fail for you?

---

Original comment by: [grasshopper](http://bitbucket.org/grasshopper)

**Comment by ingomueller-net** [comment]
https://github.com/vbabiy/bitbucket_issue_migration/issues/27

---

Original comment by: [grasshopper](http://bitbucket.org/grasshopper)

**Comment by ingomueller-net** [comment]
Maybe [this pull request](https://github.com/vbabiy/bitbucket_issue_migration/pull/18) helps us. First it lets the script print out the message of the 403 error. Second the give the tip to let your account be whitelisted for the migration...

---

Original comment by: Ingo Müller

**Comment by ingomueller-net** [comment]
try to modify the script and add a pause of 30 seconds every time an issue is imported

---

Original comment by: [grasshopper](http://bitbucket.org/grasshopper)

**Comment by ingomueller-net** [comment]
@ingomueller-net, any news?

---

Original comment by: [grasshopper](http://bitbucket.org/grasshopper)

**Comment by ingomueller-net** [comment]
[This fork](https://github.com/nskvortsov/bitbucket_issue_migration) and a delay of 10 seconds seems to work! Will run a complete test tomorrow and let you double-check the result.

---

Original comment by: Ingo Müller

**Comment by ingomueller-net** [comment]
Ok, check [this](https://github.com/g9NmIkehCleu) out. Issues seem to work, links to issues and changesets as well. Links to pull requests don't. I will also have to change the URLs inside the puppet code to clone from the new URL. If that looks good to you, I can do the same to the aegee organization. Please confirm.

What shall we do with the old projects then? In particular, how do we ensure that we don't accidentally continue with the old ones?

---

Original comment by: Ingo Müller

**Comment by ingomueller-net** [comment]
very nice!

for the old projects we can set them to private again, that'd be the fastest way that also ensure some "history"

PR aren't that important for now, we were "just learning how to use them"...

---

Original comment by: [grasshopper](http://bitbucket.org/grasshopper)

**Comment by ingomueller-net** [comment]
are you going to migrate (using ingomueller-net) and successively on aegee?

I am confused, why creating also a bogus personal account?

---

Original comment by: [grasshopper](http://bitbucket.org/grasshopper)

**Comment by ingomueller-net** [comment]
Alright, migration of repositories and issues completed. I also made the issue trackers in the bitbucket projects private, but not the repositories, because it would break links...

@serviceman, I suggest to revoke admin rights of the bitbucket projects except the "AEGEE ITC" user, but including yourself, so that no one accidentally makes changes there. Let me update the respective READMEs first, to point to the new projects. Eventually, I propose to delete the projects, so that a redirect can be set up.

I still have to change the URLs in the puppet scripts.

**Comment by ingomueller-net** [comment]
READMEs in bitbucket are updated and now link to the new projects.

**Comment by ingomueller-net** [comment]
Created [pull request](https://github.com/AEGEE/oms-development-vm/pull/24) for changing the URLs. Please review this PR and the other one. Then I'll merge to dev, test, and merge to master. After that, my part of the migration is done.

**Comment by linuxbandit** [comment]
Alright, as I mentioned in the other [repo](https://github.com/AEGEE/oms-development-vm/issues/18) there's a little more thing to do after closing this

**Comment by ingomueller-net** [comment]
@serviceman, I think we can we close this now. Updating the README in the other project is unrelated. Reopen if you disagree.
