### ISSUE TITLE
Set some sort of "debug" flag that allows for verbosity

### ISSUE THREAD

**Issue by ingomueller-net** [AEGEE/oms-core#17]
Sometimes to see if the internals of the API are good, verbosity is useful (i.e. log on console the JSON received and/or about to be returned)

---
- Bitbucket: https://bitbucket.org/ingomueller-net/oms-core/issue/17
- Originally reported by: [grasshopper](http://bitbucket.org/grasshopper)
- Originally created at: 2015-10-29T17:12:33.355

**Comment by ingomueller-net** [comment]
cleaned code, finally the ldap search isn't just copypasted through all functions.
added methods to find members of a body
closed #17

→ <<cset 47d236cfe2b4>>

---

Original comment by: [grasshopper](http://bitbucket.org/grasshopper)

**Comment by linuxbandit** [comment]
47d236c closes this, for some reason it was still open
