### ISSUE TITLE
a route <addr>/antennae/ is interpreted as with :bodyCode null

### ISSUE THREAD

**Issue by ingomueller-net** [AEGEE/oms-core#18]
I am not sure if this is just normal design of REST API (i.e. restify) but the core should have a way to spot such cases and take the best decision (i.e. considering the URL as a request for all antennae)

---
- Bitbucket: https://bitbucket.org/ingomueller-net/oms-core/issue/18
- Originally reported by: [grasshopper](http://bitbucket.org/grasshopper)
- Originally created at: 2015-11-04T16:48:05.902

**Comment by rodri4533** [comment]
From restify version 2.0 this functionality can be added using 

```
server.pre(restify.pre.sanitizePath());
```

Added this line in my **oms-core/server.js** file and it works

For further informations: https://github.com/restify/node-restify/wiki/1.4-to-2.0-Migration-Tips

**Comment by linuxbandit** [comment]
@rodri4533 :clap:

**Comment by linuxbandit** [comment]
since the trailing slash has a meaning in this kind of applications, I believe that keeping it strict can help spotting issues, thus I close it as is
