### ISSUE TITLE
make createUser and createAntenna handle name collisions

### ISSUE THREAD

**Issue by ingomueller-net** [AEGEE/oms-core#2]
As the first implementation is a naive approach, I did not care to handle multiple names

---
- Bitbucket: https://bitbucket.org/ingomueller-net/oms-core/issue/2
- Originally reported by: [grasshopper](http://bitbucket.org/grasshopper)
- Originally created at: 2015-05-25T18:01:57.347

**Comment by linuxbandit** [comment]
About createUser: 

https://github.com/AEGEE/oms-core/blob/dev/lib/core.js#L170

you can see the username is just created by having first and last name separated by a dot. This is a very basic scenario that does not work if
- user "name.surname already" exists;
- does not handle multiple names (e.g. Portuguese, Spanish - Don Diego de la Vega, Don Quixote de la Mancha)
