### ISSUE TITLE
Set some github usage conventions

### ISSUE THREAD

**Issue by linuxbandit** [AEGEE/oms-core#23]
Have a look at this: https://github.com/AEGEE/oms-core/wiki/Github-usage-conventions

The first two, as @ingomueller-net can recognise, are the suggestions coming from him. Good practices.

Let's add some more that can be useful

**Comment by ingomueller-net** [comment]
Good idea!

Open question: who merges `dev` to `master` and when?

**Comment by linuxbandit** [comment]
According to nvie.com's article, when we reach a release version we merge and tag.

At this stage, we (I) can merge every now and then and tag a minor, but later we'll have @zborna tell us the milestones and such, to plan releases

**Comment by blacksph3re** [comment]
When you are talking about the git workflow, I can recomment [Git-Flow](http://nvie.com/posts/a-successful-git-branching-model/). But your's is already going into that direction, the important thing is just that whatever is on master has to work. 
Especially in a early phase of the project that is really difficult to accomplish and may seem unnecessary, but as soon as something like a "hotfix" is really needed that branching model will pay off.
