### ISSUE TITLE
Create admin of organisation not tied to any of our personal account

### ISSUE THREAD

**Issue by linuxbandit** [AEGEE/oms-core#31]
As Philipp Von Klitzing suggested, we should make itc@aegee.org (the ITC board) have a github account and make him co-owner of the organisation, in order to be safe if both me and you are unable to "pass on" the admin rights. The password is shared as like the other ones of the ITC board

**Comment by ingomueller-net** [comment]
You will have to make me owner before I can work on this issue.

**Comment by ingomueller-net** [comment]
[Done](https://github.com/orgs/AEGEE/people?utf8=%E2%9C%93&query=aegee).
