### ISSUE TITLE
Move our own source files to a subfolder

### ISSUE THREAD

**Issue by ingomueller-net** [AEGEE/oms-core#32]
At the moment it is only `core.js` and `server.js`, but they may grow more. Also they are different from `README.md` etc. I believe nodejs conventions put these into a folder `lib`.

**Comment by linuxbandit** [comment]
see [this answer](http://stackoverflow.com/a/20885809)

**Comment by linuxbandit** [comment]
also I am using [this structure](https://scotch.io/tutorials/easy-node-authentication-setup-and-local#application-structure) inside the module I am writing, with the difference that all you see there is into a lib/ folder, and package.json is outside of it

**Comment by linuxbandit** [comment]
I can do it in my next commit, so I assign myself (if not ok, reassign yourself)

**Comment by linuxbandit** [comment]
completed, but won't be closed (automatically by github) until I merge into master, I presume
