### ISSUE TITLE
OAuth / SAML

### ISSUE THREAD

**Issue by ingomueller-net** [AEGEE/oms-core#5]
Investigate about that

---
- Bitbucket: https://bitbucket.org/ingomueller-net/oms-core/issue/5
- Originally reported by: [grasshopper](http://bitbucket.org/grasshopper)
- Originally created at: 2015-05-25T20:14:22.053

**Comment by ingomueller-net** [comment]
OAuth seems insecure and apparently SAML could make up to it. What do you think?

Especially @ingomueller-net since you mentioned SAML and investigated it

---

Original comment by: [grasshopper](http://bitbucket.org/grasshopper)

**Comment by ingomueller-net** [comment]
https://blog.surfnet.nl/en/saml-for-dummies/

where in our case:
- IdP is OMS-core
- SP is any OMS module, and also external apps (Antennae-specific modules, EUth liquid democracy stuff)

---

Original comment by: [grasshopper](http://bitbucket.org/grasshopper)

**Comment by ingomueller-net** [comment]
1. https://github.com/auth0/node-samlp
2. https://github.com/Clever/saml2

maybe these are libraries that allows the core to implement IdP
(we are looking for something similar to [this python](https://github.com/rohe/pysaml2) or [this php](https://simplesamlphp.org/))

---

Original comment by: [grasshopper](http://bitbucket.org/grasshopper)

**Comment by ingomueller-net** [comment]
for python, other stuff:
- https://github.com/pitbulk/python3-saml
- https://github.com/onelogin/python-saml

and general js library: http://passportjs.org/ ( for oms-modules --i.e. service providers, if developed in js )

---

Original comment by: [grasshopper](http://bitbucket.org/grasshopper)

**Comment by ingomueller-net** [comment]
Passportjs looks great. It also provides a saml iplementation, so best of both. I think it is a great start as initial authentication middleware: https://github.com/bergie/passport-saml

---

Original comment by: [mauritskorse](http://bitbucket.org/mauritskorse)

**Comment by ingomueller-net** [comment]
marked as that so I start working on that first thing when in Bxl

---

Original comment by: [grasshopper](http://bitbucket.org/grasshopper)

**Comment by ingomueller-net** [comment]
I think SAML and OAuth are complementary:
- If a service needs to get information _about a user_ from a trusted authority (for example to know what groups she/he is in, e-mail addresses, has payed or not), you need SAML. I.e., the "Service Provider" askes the "Identity Provider": "give me information about that guy that I can trust".
- If a web app/form a mobile app needs to see content of a service "with the eyes" (i.e., with the permissions) of the currently logged-in user, you need OAuth. I.e., the app asks the service: "this guy wants to see that content, here you have his token, give me the content".

---

Original comment by: Ingo Müller

**Comment by linuxbandit** [comment]
as per [here](http://www.softwaresecured.com/2013/07/16/federated-identities-openid-vs-saml-vs-oauth/) I think SAML is just not applicable at this stage

The reason is that SAML is for making a IdP and SP communicate, but our core should both authenticate and provide the service (the API), so no communication between separated servers is in the picture

(in other words, when I wrote "SP is any OMS module, and also external apps (Antennae-specific modules, EUth liquid democracy stuff)" I believe I was wrong). Or maybe I am wrong now, I still have to figure this out and realise who are the actors

**Comment by ingomueller-net** [comment]
I agree that SAML does not help us to authorize REST API calls. People seem to use some token-based approach like OAuth.

Not too sure what to do with it yet, but I found out that passport can use SAML as strategy: https://github.com/bergie/passport-saml

**Comment by ingomueller-net** [comment]
Maybe [this stackoverflow post](http://stackoverflow.com/questions/6068113/do-sessions-really-violate-restfulness) is helpful?
