### ISSUE TITLE
verifyToken passing user details

### ISSUE THREAD

**Issue by blacksph3re** [AEGEE/oms-core#59]
It would be lovely if the verifyToken method (see /lib/core.js in the beginning...) could forward user details, at least the ID to following req handlers, so it can be used to store stuff like "creator" or in my case an initial event owner (and most likely more).

**Comment by linuxbandit** [comment]
this is going to change soon as the tokenMaster will handle the tokens

as of right now, the tokenMaster (redis) gets a token and checks if it's a key, and returns the value which is the name of the service

**Comment by blacksph3re** [comment]
OK, then I assume it's already there. Will take some time until I really need it anyways. Thanks!
