### ISSUE TITLE
Possible integration with MS Office 365 (Azure)

### ISSUE THREAD

**Issue by ingomueller-net** [AEGEE/oms-core#6]
For possible integration of the OMS with MS Office 365 service the core could push updates to the MS Azure REST API. There is a NodeJs library available: https://github.com/AzureADSamples/WebAPI-Nodejs

---
- Bitbucket: https://bitbucket.org/ingomueller-net/oms-core/issue/6
- Originally reported by: [mauritskorse](http://bitbucket.org/mauritskorse)
- Originally created at: 2015-06-21T23:15:42.327

**Comment by linuxbandit** [comment]
this looks easier https://github.com/eleith/emailjs

I am implementing it now
